import requests
# Replace with your real ID token
ID_TOKEN = "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg3NzQ4NTAwMmYwNWJlMDI2N2VmNDU5ZjViNTEzNTMzYjVjNThjMTIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiQW5raXRoIEdhbmppIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0tzYVZoeGlhWS1WczRwcHJCRkpPUmpDOEN5bkwyZmVXRHV0QUdkMEJaNjJzWnJ0ZkU9czk2LWMiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbGVldGNvZGUtc3BhY2VkLXJlcCIsImF1ZCI6ImxlZXRjb2RlLXNwYWNlZC1yZXAiLCJhdXRoX3RpbWUiOjE3NTE2NDgxNDksInVzZXJfaWQiOiJGTktSNzlUUW11WUNGS0xIcXNBeE1LMERjcEIyIiwic3ViIjoiRk5LUjc5VFFtdVlDRktMSHFzQXhNSzBEY3BCMiIsImlhdCI6MTc1MTY0ODE0OSwiZXhwIjoxNzUxNjUxNzQ5LCJlbWFpbCI6ImdhbmppYW5raXRoQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTA4MzM0MjUyNzQzNjMzMjE1ODMxIl0sImVtYWlsIjpbImdhbmppYW5raXRoQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6Imdvb2dsZS5jb20ifX0.pQfu0til1UJMYtYZpbSPkhfW_CD3s0zaGoOcW95YW7IAudKpt81aoRSyj689oGO7Csn-3qzEyePDawfTRaOGW0n6lYfUrwaD0zPlboWxBQGZ2JRSWSB4HAEDU8BAJX3tyA0xlXiumdXoH8aCu27k0U5xdQpkeswpdMS3SWIfpwIadO_S5AdiqB7yYyLwLAq7hXNm8KFh_HeJQIPriRGmbWFFolVbwbRAZA4A4A8wfJbM3nwmMSLDeP-9iMdHFBY3zRR-R9dlYROa6tmvMcnhvN0IBuAD6mVtF7cEq-rt47bqLYqBjemzUt3PWIiSNiyBk6mQUzUHkw0F45jwO0W2eg"

headers = {
    "Authorization": f"Bearer {ID_TOKEN}"
}

res = requests.get("http://localhost:8000/reviews", headers=headers)

print("Status Code:", res.status_code)
print("Response:", res.json())
